spring:
  profiles:
    include:
    - common-prod

mybatis:
  type-aliases-package: com.edu.exmg.core.bean
  mapper-locations: classpath*:mapper/**.xml,classpath*:mapper/ext/**.xml

files:
  upload:
    absolutePath: /home/admin/exmg/admin/public/static
    relativePath: /static