server:
  port: 9082
  servlet:
    context-path: /api/exmg
spring:
  application:
    name: exmg
  profiles:
    active: dev

files:
  upload:
    absolutePath: /home/admin/exmg/admin/public/static
    relativePath: /static/images